### 作業
目前已經學過許多的模型，相信大家對整體流程應該比較掌握了，這次作業請改用**手寫辨識資料集**，步驟流程都是一樣的，請試著自己撰寫程式碼來完成所有步驟

In [83]:
from sklearn import datasets, metrics
digits = datasets.load_digits()
#digits

In [94]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
import numpy as np

x_train, x_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.2, random_state=1234)

gbdt = GradientBoostingClassifier(learning_rate=0.2, n_estimators=100, max_depth=3, random_state=0)
gbdt.fit(x_train, y_train)
y_pred = gbdt.predict(x_test)
#print(y_pred)

acc = metrics.accuracy_score(y_test, y_pred)
print("Acuuracy: ", acc)
print("Misclassified sample: %d" % (y_test != y_pred).sum())

#print("Feature importance: ", gbdt.feature_importances_)

y_pred_ave = gbdt.predict_proba(x_test)
y_pred_ave = np.argmax(y_pred_ave, axis=1)
confmat = metrics.confusion_matrix(y_test, y_pred_ave)
print('target names: ' + str(digits.target_names))
print('confusion matrix:')
print(confmat)

Acuuracy:  0.9805555555555555
Misclassified sample: 7
target names: [0 1 2 3 4 5 6 7 8 9]
confusion matrix:
[[28  0  0  0  0  0  0  0  0  0]
 [ 0 40  0  0  0  0  0  0  0  0]
 [ 0  0 38  0  0  0  0  0  0  0]
 [ 0  0  0 36  0  0  0  0  0  0]
 [ 0  0  0  0 42  1  0  1  0  0]
 [ 0  0  0  0  0 41  0  0  0  0]
 [ 0  0  0  0  0  0 32  0  1  0]
 [ 0  0  0  0  1  0  0 33  0  0]
 [ 0  1  0  0  0  1  0  0 30  0]
 [ 0  0  0  0  0  0  0  1  0 33]]
