# 作業目標:

    使用CIFAR100, 數據集變大的影響
    
    
# 作業重點:¶

   了解 CIFAR100 跟 CIFAR10 數據及差異


In [2]:
import numpy
from keras.datasets import cifar100
import numpy as np


import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
import h5py
warnings.resetwarnings()

np.random.seed(100)

# 資料準備

In [3]:
(x_img_train,y_label_train), \
(x_img_test, y_label_test)=cifar100.load_data()

print('train:',len(x_img_train))
print('test :',len(x_img_test))

169009152/169001437 [==============================] - 27s 0us/step
train: 50000
test : 10000


In [6]:
# 查詢檔案維度資訊
x_img_train.shape, y_label_train.shape, x_img_test.shape, y_label_test.shape

((50000, 32, 32, 3), (50000, 1), (10000, 32, 32, 3), (10000, 1))

The CIFAR-100 dataset
This dataset is just like the CIFAR-10, except it has 100 classes containing 600 images each. There are 500 training images and 100 testing images per class. The 100 classes in the CIFAR-100 are grouped into 20 superclasses. Each image comes with a "fine" label (the class to which it belongs) and a "coarse" label (the superclass to which it belongs).
Here is the list of classes in the CIFAR-100:

    Superclass	Classes
    aquatic mammals	beaver, dolphin, otter, seal, whale
    fish	aquarium fish, flatfish, ray, shark, trout
    flowers	orchids, poppies, roses, sunflowers, tulips
    food containers	bottles, bowls, cans, cups, plates
    fruit and vegetables	apples, mushrooms, oranges, pears, sweet peppers
    household electrical devices	clock, computer keyboard, lamp, telephone, television
    household furniture	bed, chair, couch, table, wardrobe
    insects	bee, beetle, butterfly, caterpillar, cockroach
    large carnivores	bear, leopard, lion, tiger, wolf
    large man-made outdoor things	bridge, castle, house, road, skyscraper
    large natural outdoor scenes	cloud, forest, mountain, plain, sea
    large omnivores and herbivores	camel, cattle, chimpanzee, elephant, kangaroo
    medium-sized mammals	fox, porcupine, possum, raccoon, skunk
    non-insect invertebrates	crab, lobster, snail, spider, worm
    people	baby, boy, girl, man, woman
    reptiles	crocodile, dinosaur, lizard, snake, turtle
    small mammals	hamster, mouse, rabbit, shrew, squirrel
    trees	maple, oak, palm, pine, willow
    vehicles 1	bicycle, bus, motorcycle, pickup truck, train
    vehicles 2	lawn-mower, rocket, streetcar, tank, tractor

# Image normalize 

In [12]:
x_img_train[0][0][1]

array([255, 255, 255], dtype=uint8)

In [13]:
x_img_train_normalize = x_img_train.astype('float32') / 255.0
x_img_test_normalize = x_img_test.astype('float32') / 255.0

array([1., 1., 1.], dtype=float32)

In [16]:
x_img_train_normalize[1][0][9]

array([0.99215686, 0.99215686, 0.99215686], dtype=float32)

# 轉換label 為OneHot Encoding

In [20]:
y_label_train.shape

(50000, 1)

In [19]:
y_label_train[:5]

array([[19],
       [29],
       [ 0],
       [11],
       [ 1]])

In [21]:
from keras.utils import np_utils
y_label_train_OneHot = np_utils.to_categorical(y_label_train)
y_label_test_OneHot = np_utils.to_categorical(y_label_test)

In [22]:
y_label_train_OneHot.shape

(50000, 100)

In [23]:
y_label_train_OneHot[:5]

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.